FORMAT: 1A
HOST: http://localhost:8181/

# catalog

Polls is a simple API allowing consumers to view polls and vote in them.

## Category List [/catalog/categories/list]

### List All Categories [GET]

+ Response 200 (application/json)
    + Attributes (array[number])
    + Body

            [
                1,
                2,
                3
            ]

## Category Detail [/catalog/categories/{category_id}]

+ Parameters
    + category_id: `1` (number, required) - ID of a category

### Get Category [GET]

+ Response 200 (application/json)
    + Attributes (Category)
    + Body

            {
                "id": 1,
                "name": "Software"
            }

## Product List [/catalog/products/list]

### List All [GET]

+ Response 200 (application/json)
    + Attributes (array[number])
    + Body

            [
                1,
                2,
                3
            ]

## Product By Category List [/catalog/products/list/{category_id}]

+ Parameters
    + category_id: `1` (number, required) - ID of a category

### List All [GET]

+ Response 200 (application/json)
    + Attributes (array[number])
    + Body

            [
                1,
                2
            ]

## Product Detail [/catalog/products/{product_id}]

+ Parameters
    + product_id: `1` (number, required) - ID of a product

### Get Product By Id [GET]

+ Response 200 (application/json)
    + Attributes (Product)
    + Body

            {
                "id": 1,
                "catId": [ 1 ],
                "name": "Linux",
                "description": "OSOS",
                "image": "img/linux.png"
            }

## Data Structures

### Category
+ id: `1` (number, required) - unique identirier
+ name: `Software` (string, required) - human readable name

### Product
+ id: `1` (number, required) - unique identifier
+ catId (array[number], required) - list of category identifiers
+ name: `Notepad++` (string, required) - human readable name of product
+ description: `Text editor on steroids` (string, optional) - human readable description of product
+ image: `img/notepad.png` (string, optional) - relative path to static image
