FORMAT: 1A
HOST: http://localhost:8181/

# catalog

Polls is a simple API allowing consumers to view polls and vote in them.

## Category List [/catalog/categories/list]

### List All Categories [GET]

+ Response 200 (application/json)

        [
            1,
            2,
            3
        ]

## Category Detail [/catalog/categories/1]

### Get Category [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Software"
        }

## Product List [/catalog/products/list]

### List All Products [GET]

+ Response 200 (application/json)

        [
            1,
            2,
            3
        ]

## Product By Category List [/catalog/products/list/1]

### List All Products [GET]

+ Response 200 (application/json)

        [
            1,
            2
        ]

## Product Detail [/catalog/products/1]

### Get Product By Id [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "catId": [ 1 ],
            "name": "Linux",
            "description": "OSOS",
            "image": "img/linux.png"
        }